// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadConfig() {
  return window['go']['controller']['ConfigController']['ReadConfig']();
}

export function WriteConfig(arg1) {
  return window['go']['controller']['ConfigController']['WriteConfig'](arg1);
}
