// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {config} from '../models';

export function ReadConfig():Promise<result.RtnData>;

export function WriteConfig(arg1:config.ApplicationConfig):Promise<result.RtnMessage>;
