// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindCourseInfoList() {
  return window['go']['controller']['CourseInfoController']['FindCourseInfoList']();
}

export function FindCourseInfoListWithRival(arg1) {
  return window['go']['controller']['CourseInfoController']['FindCourseInfoListWithRival'](arg1);
}

export function GENERATOR_COURSE_INFO() {
  return window['go']['controller']['CourseInfoController']['GENERATOR_COURSE_INFO']();
}

export function GENERATOR_COURSE_INFO_DTO() {
  return window['go']['controller']['CourseInfoController']['GENERATOR_COURSE_INFO_DTO']();
}
