// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {entity} from '../models';
import {dto} from '../models';

export function FindCourseInfoList():Promise<result.RtnDataList>;

export function FindCourseInfoListWithRival(arg1:number):Promise<result.RtnDataList>;

export function GENERATOR_COURSE_INFO():Promise<entity.CourseInfo>;

export function GENERATOR_COURSE_INFO_DTO():Promise<dto.CourseInfoDto>;
