// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {dto} from '../models';
import {entity} from '../models';

export function AddDiffTableHeader(arg1:string):Promise<result.RtnMessage>;

export function DelDiffTableHeader(arg1:number):Promise<result.RtnMessage>;

export function FindDiffTableHeaderList():Promise<result.RtnDataList>;

export function FindDiffTableHeaderListWithRival(arg1:number):Promise<result.RtnDataList>;

export function FindDiffTableHeaderTree():Promise<result.RtnDataList>;

export function GENERATOR_TABLE_DATA():Promise<dto.DiffTableDataDto>;

export function GENERATOR_TABLE_HEADER():Promise<entity.DiffTableHeader>;

export function GENERATOR_TABLE_HEADER_DTO():Promise<dto.DiffTableHeaderDto>;

export function QueryDiffTableDataWithRival(arg1:number,arg2:string,arg3:number):Promise<result.RtnDataList>;

export function QueryDiffTableInfoById(arg1:number):Promise<result.RtnData>;

export function QueryDiffTableInfoWithRival(arg1:number,arg2:number):Promise<result.RtnData>;

export function QueryLevelLayeredDiffTableInfoById(arg1:number):Promise<result.RtnData>;
