// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDiffTableHeader(arg1) {
  return window['go']['controller']['DiffTableController']['AddDiffTableHeader'](arg1);
}

export function FindDiffTableHeader() {
  return window['go']['controller']['DiffTableController']['FindDiffTableHeader']();
}
