// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDiffTableHeader(arg1) {
  return window['go']['controller']['DiffTableController']['AddDiffTableHeader'](arg1);
}

export function DelDiffTableHeader(arg1) {
  return window['go']['controller']['DiffTableController']['DelDiffTableHeader'](arg1);
}

export function FindDiffTableHeaderList() {
  return window['go']['controller']['DiffTableController']['FindDiffTableHeaderList']();
}

export function GENERATOR_TABLE_HEADER() {
  return window['go']['controller']['DiffTableController']['GENERATOR_TABLE_HEADER']();
}
