// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function AddDiffTableHeader(arg1:string):Promise<entity.DiffTableHeader>;
