// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDiffTableHeader(arg1) {
  return window['go']['controller']['DiffTableController']['AddDiffTableHeader'](arg1);
}

export function DelDiffTableHeader(arg1) {
  return window['go']['controller']['DiffTableController']['DelDiffTableHeader'](arg1);
}

export function FindDiffTableHeaderList() {
  return window['go']['controller']['DiffTableController']['FindDiffTableHeaderList']();
}

export function FindDiffTableHeaderListWithRival(arg1) {
  return window['go']['controller']['DiffTableController']['FindDiffTableHeaderListWithRival'](arg1);
}

export function FindDiffTableHeaderTree() {
  return window['go']['controller']['DiffTableController']['FindDiffTableHeaderTree']();
}

export function GENERATOR_TABLE_DATA() {
  return window['go']['controller']['DiffTableController']['GENERATOR_TABLE_DATA']();
}

export function GENERATOR_TABLE_HEADER() {
  return window['go']['controller']['DiffTableController']['GENERATOR_TABLE_HEADER']();
}

export function GENERATOR_TABLE_HEADER_DTO() {
  return window['go']['controller']['DiffTableController']['GENERATOR_TABLE_HEADER_DTO']();
}

export function QueryDiffTableInfoById(arg1) {
  return window['go']['controller']['DiffTableController']['QueryDiffTableInfoById'](arg1);
}

export function QueryDiffTableInfoWithRival(arg1, arg2) {
  return window['go']['controller']['DiffTableController']['QueryDiffTableInfoWithRival'](arg1, arg2);
}

export function QueryLevelLayeredDiffTableInfoById(arg1) {
  return window['go']['controller']['DiffTableController']['QueryLevelLayeredDiffTableInfoById'](arg1);
}
