// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {entity} from '../models';

export function AddDiffTableHeader(arg1:string):Promise<result.RtnMessage>;

export function DelDiffTableHeader(arg1:number):Promise<result.RtnMessage>;

export function FindDiffTableHeaderList():Promise<result.RtnDataList>;

export function GENERATOR_TABLE_HEADER():Promise<entity.DiffTableHeader>;
