// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['controller']['FolderController']['AddFolder'](arg1);
}

export function DelFolder(arg1) {
  return window['go']['controller']['FolderController']['DelFolder'](arg1);
}

export function DelFolderContent(arg1) {
  return window['go']['controller']['FolderController']['DelFolderContent'](arg1);
}

export function FindFolderList() {
  return window['go']['controller']['FolderController']['FindFolderList']();
}

export function FindFolderTree() {
  return window['go']['controller']['FolderController']['FindFolderTree']();
}

export function GENERATOR_FOLDER() {
  return window['go']['controller']['FolderController']['GENERATOR_FOLDER']();
}

export function GENERATOR_FOLDER_CONTENT_DTO() {
  return window['go']['controller']['FolderController']['GENERATOR_FOLDER_CONTENT_DTO']();
}

export function GENERATOR_FOLDER_DEFINITION_DTO() {
  return window['go']['controller']['FolderController']['GENERATOR_FOLDER_DEFINITION_DTO']();
}

export function GENERATOR_FOLDER_DTO() {
  return window['go']['controller']['FolderController']['GENERATOR_FOLDER_DTO']();
}

export function QueryFolderDefinition() {
  return window['go']['controller']['FolderController']['QueryFolderDefinition']();
}

export function SyncSongData() {
  return window['go']['controller']['FolderController']['SyncSongData']();
}
