// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryUserInfoByID(arg1) {
  return window['go']['controller']['RivalInfoController']['QueryUserInfoByID'](arg1);
}

export function SyncRivalScoreLog(arg1) {
  return window['go']['controller']['RivalInfoController']['SyncRivalScoreLog'](arg1);
}
