// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GENERATE_RIVAL_SCORE_LOG() {
  return window['go']['controller']['RivalScoreLogController']['GENERATE_RIVAL_SCORE_LOG']();
}

export function QueryRivalScoreLogPageList(arg1) {
  return window['go']['controller']['RivalScoreLogController']['QueryRivalScoreLogPageList'](arg1);
}
