// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function QueryUserInfoByID(arg1:number):Promise<entity.RivalInfo>;

export function SyncRivalScoreLog(arg1:number):Promise<void>;
