// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindRivalSongDataToFolder(arg1, arg2) {
  return window['go']['controller']['RivalSongDataController']['BindRivalSongDataToFolder'](arg1, arg2);
}

export function GENERATE_RIVAL_SONG_DATA_DTO() {
  return window['go']['controller']['RivalSongDataController']['GENERATE_RIVAL_SONG_DATA_DTO']();
}
