// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {vo} from '../models';
import {result} from '../models';

export function GENERATE_RIVAL_SCORE_LOG():Promise<dto.RivalScoreLogDto>;

export function QueryRivalScoreLogPageList(arg1:vo.RivalScoreLogVo):Promise<result.RtnDataList>;
