// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {entity} from '../models';
import {dto} from '../models';

export function DelRivalInfo(arg1:number):Promise<result.RtnMessage>;

export function FindRivalInfoList():Promise<result.RtnDataList>;

export function GENERATOR_RIVAL_INFO():Promise<entity.RivalInfo>;

export function GENERATOR_RIVAL_INFO_DTO():Promise<dto.RivalInfoDto>;

export function InitializeMainUser(arg1:entity.RivalInfo):Promise<result.RtnMessage>;

export function QueryMainUser():Promise<result.RtnData>;

export function QueryUserInfoByID(arg1:number):Promise<result.RtnData>;

export function QueryUserInfoWithLevelLayeredDiffTableLampStatus(arg1:number,arg2:number):Promise<result.RtnData>;

export function QueryUserPlayCountInYear(arg1:number,arg2:number):Promise<result.RtnDataList>;

export function SyncRivalScoreLog(arg1:number):Promise<result.RtnMessage>;
