// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRivalTag(arg1) {
  return window['go']['controller']['RivalTagController']['AddRivalTag'](arg1);
}

export function DeleteRivalTagByID(arg1) {
  return window['go']['controller']['RivalTagController']['DeleteRivalTagByID'](arg1);
}

export function FindRivalTagList(arg1) {
  return window['go']['controller']['RivalTagController']['FindRivalTagList'](arg1);
}

export function GENERATE_RIVAL_TAG() {
  return window['go']['controller']['RivalTagController']['GENERATE_RIVAL_TAG']();
}

export function GENERATE_RIVAL_TAG_DTO() {
  return window['go']['controller']['RivalTagController']['GENERATE_RIVAL_TAG_DTO']();
}

export function QueryRivalTagPageList(arg1) {
  return window['go']['controller']['RivalTagController']['QueryRivalTagPageList'](arg1);
}

export function RevertRivalTagEnabledState(arg1) {
  return window['go']['controller']['RivalTagController']['RevertRivalTagEnabledState'](arg1);
}
