// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {result} from '../models';
import {dto} from '../models';

export function BindRivalSongDataToFolder(arg1:number,arg2:Array<number>):Promise<result.RtnMessage>;

export function GENERATE_RIVAL_SONG_DATA_DTO():Promise<dto.RivalSongDataDto>;
