// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DelRivalInfo(arg1) {
  return window['go']['controller']['RivalInfoController']['DelRivalInfo'](arg1);
}

export function FindRivalInfoList() {
  return window['go']['controller']['RivalInfoController']['FindRivalInfoList']();
}

export function GENERATOR_RIVAL_INFO() {
  return window['go']['controller']['RivalInfoController']['GENERATOR_RIVAL_INFO']();
}

export function QueryUserInfoByID(arg1) {
  return window['go']['controller']['RivalInfoController']['QueryUserInfoByID'](arg1);
}

export function SyncRivalScoreLog(arg1) {
  return window['go']['controller']['RivalInfoController']['SyncRivalScoreLog'](arg1);
}
