// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDiffTableHeader(arg1) {
  return window['go']['main']['App']['AddDiffTableHeader'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function AddRivalInfo(arg1) {
  return window['go']['main']['App']['AddRivalInfo'](arg1);
}

export function AddRivalTag(arg1) {
  return window['go']['main']['App']['AddRivalTag'](arg1);
}

export function BindDiffTableDataToFolder(arg1, arg2) {
  return window['go']['main']['App']['BindDiffTableDataToFolder'](arg1, arg2);
}

export function BindRivalSongDataToFolder(arg1, arg2) {
  return window['go']['main']['App']['BindRivalSongDataToFolder'](arg1, arg2);
}

export function DelDiffTableHeader(arg1) {
  return window['go']['main']['App']['DelDiffTableHeader'](arg1);
}

export function DelFolder(arg1) {
  return window['go']['main']['App']['DelFolder'](arg1);
}

export function DelFolderContent(arg1) {
  return window['go']['main']['App']['DelFolderContent'](arg1);
}

export function DelRivalInfo(arg1) {
  return window['go']['main']['App']['DelRivalInfo'](arg1);
}

export function DeleteRivalTagByID(arg1) {
  return window['go']['main']['App']['DeleteRivalTagByID'](arg1);
}

export function FindCourseInfoList() {
  return window['go']['main']['App']['FindCourseInfoList']();
}

export function FindCourseInfoListWithRival(arg1) {
  return window['go']['main']['App']['FindCourseInfoListWithRival'](arg1);
}

export function FindDiffTableHeaderList() {
  return window['go']['main']['App']['FindDiffTableHeaderList']();
}

export function FindDiffTableHeaderListWithRival(arg1) {
  return window['go']['main']['App']['FindDiffTableHeaderListWithRival'](arg1);
}

export function FindDiffTableHeaderTree(arg1) {
  return window['go']['main']['App']['FindDiffTableHeaderTree'](arg1);
}

export function FindDiffTableHeaderTreeWithRival(arg1) {
  return window['go']['main']['App']['FindDiffTableHeaderTreeWithRival'](arg1);
}

export function FindFolderContentList(arg1) {
  return window['go']['main']['App']['FindFolderContentList'](arg1);
}

export function FindFolderList(arg1) {
  return window['go']['main']['App']['FindFolderList'](arg1);
}

export function FindFolderTree(arg1) {
  return window['go']['main']['App']['FindFolderTree'](arg1);
}

export function FindRivalInfoList() {
  return window['go']['main']['App']['FindRivalInfoList']();
}

export function FindRivalTagList(arg1) {
  return window['go']['main']['App']['FindRivalTagList'](arg1);
}

export function GENERATE_RIVAL_SCORE_LOG() {
  return window['go']['main']['App']['GENERATE_RIVAL_SCORE_LOG']();
}

export function GENERATE_RIVAL_SONG_DATA_DTO() {
  return window['go']['main']['App']['GENERATE_RIVAL_SONG_DATA_DTO']();
}

export function GENERATE_RIVAL_TAG() {
  return window['go']['main']['App']['GENERATE_RIVAL_TAG']();
}

export function GENERATE_RIVAL_TAG_DTO() {
  return window['go']['main']['App']['GENERATE_RIVAL_TAG_DTO']();
}

export function GENERATOR_COURSE_INFO() {
  return window['go']['main']['App']['GENERATOR_COURSE_INFO']();
}

export function GENERATOR_COURSE_INFO_DTO() {
  return window['go']['main']['App']['GENERATOR_COURSE_INFO_DTO']();
}

export function GENERATOR_FOLDER() {
  return window['go']['main']['App']['GENERATOR_FOLDER']();
}

export function GENERATOR_FOLDER_CONTENT_DTO() {
  return window['go']['main']['App']['GENERATOR_FOLDER_CONTENT_DTO']();
}

export function GENERATOR_FOLDER_DEFINITION_DTO() {
  return window['go']['main']['App']['GENERATOR_FOLDER_DEFINITION_DTO']();
}

export function GENERATOR_FOLDER_DTO() {
  return window['go']['main']['App']['GENERATOR_FOLDER_DTO']();
}

export function GENERATOR_RIVAL_INFO() {
  return window['go']['main']['App']['GENERATOR_RIVAL_INFO']();
}

export function GENERATOR_RIVAL_INFO_DTO() {
  return window['go']['main']['App']['GENERATOR_RIVAL_INFO_DTO']();
}

export function GENERATOR_TABLE_DATA() {
  return window['go']['main']['App']['GENERATOR_TABLE_DATA']();
}

export function GENERATOR_TABLE_HEADER() {
  return window['go']['main']['App']['GENERATOR_TABLE_HEADER']();
}

export function GENERATOR_TABLE_HEADER_DTO() {
  return window['go']['main']['App']['GENERATOR_TABLE_HEADER_DTO']();
}

export function InitializeMainUser(arg1) {
  return window['go']['main']['App']['InitializeMainUser'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function QueryDiffTableDataWithRival(arg1) {
  return window['go']['main']['App']['QueryDiffTableDataWithRival'](arg1);
}

export function QueryDiffTableInfoById(arg1) {
  return window['go']['main']['App']['QueryDiffTableInfoById'](arg1);
}

export function QueryDiffTableInfoWithRival(arg1, arg2) {
  return window['go']['main']['App']['QueryDiffTableInfoWithRival'](arg1, arg2);
}

export function QueryFolderDefinition() {
  return window['go']['main']['App']['QueryFolderDefinition']();
}

export function QueryLevelLayeredDiffTableInfoByID(arg1) {
  return window['go']['main']['App']['QueryLevelLayeredDiffTableInfoByID'](arg1);
}

export function QueryMainUser() {
  return window['go']['main']['App']['QueryMainUser']();
}

export function QueryPrevDayScoreLogList(arg1) {
  return window['go']['main']['App']['QueryPrevDayScoreLogList'](arg1);
}

export function QueryRivalInfoPageList(arg1) {
  return window['go']['main']['App']['QueryRivalInfoPageList'](arg1);
}

export function QueryRivalPlayedYears(arg1) {
  return window['go']['main']['App']['QueryRivalPlayedYears'](arg1);
}

export function QueryRivalScoreLogPageList(arg1) {
  return window['go']['main']['App']['QueryRivalScoreLogPageList'](arg1);
}

export function QueryRivalTagPageList(arg1) {
  return window['go']['main']['App']['QueryRivalTagPageList'](arg1);
}

export function QueryUserInfoByID(arg1) {
  return window['go']['main']['App']['QueryUserInfoByID'](arg1);
}

export function QueryUserInfoWithLevelLayeredDiffTableLampStatus(arg1, arg2) {
  return window['go']['main']['App']['QueryUserInfoWithLevelLayeredDiffTableLampStatus'](arg1, arg2);
}

export function QueryUserPlayCountInYear(arg1, arg2) {
  return window['go']['main']['App']['QueryUserPlayCountInYear'](arg1, arg2);
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function RevertRivalTagEnabledState(arg1) {
  return window['go']['main']['App']['RevertRivalTagEnabledState'](arg1);
}

export function RunServer() {
  return window['go']['main']['App']['RunServer']();
}

export function SyncRivalDataByID(arg1) {
  return window['go']['main']['App']['SyncRivalDataByID'](arg1);
}

export function SyncRivalTag(arg1) {
  return window['go']['main']['App']['SyncRivalTag'](arg1);
}

export function UpdateDiffTableHeader(arg1) {
  return window['go']['main']['App']['UpdateDiffTableHeader'](arg1);
}

export function UpdateHeaderLevelOrders(arg1) {
  return window['go']['main']['App']['UpdateHeaderLevelOrders'](arg1);
}

export function UpdateHeaderOrder(arg1) {
  return window['go']['main']['App']['UpdateHeaderOrder'](arg1);
}

export function UpdateRivalInfo(arg1) {
  return window['go']['main']['App']['UpdateRivalInfo'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
