// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBatchDiffTableHeader(arg1) {
  return window['go']['main']['App']['AddBatchDiffTableHeader'](arg1);
}

export function AddCustomCourse(arg1) {
  return window['go']['main']['App']['AddCustomCourse'](arg1);
}

export function AddCustomCourseData(arg1) {
  return window['go']['main']['App']['AddCustomCourseData'](arg1);
}

export function AddCustomDiffTable(arg1) {
  return window['go']['main']['App']['AddCustomDiffTable'](arg1);
}

export function AddDiffTableHeader(arg1) {
  return window['go']['main']['App']['AddDiffTableHeader'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function AddRivalInfo(arg1) {
  return window['go']['main']['App']['AddRivalInfo'](arg1);
}

export function AddRivalTag(arg1) {
  return window['go']['main']['App']['AddRivalTag'](arg1);
}

export function BindFolderContentToCustomCourse(arg1, arg2) {
  return window['go']['main']['App']['BindFolderContentToCustomCourse'](arg1, arg2);
}

export function BindSongToCustomCourse(arg1, arg2, arg3) {
  return window['go']['main']['App']['BindSongToCustomCourse'](arg1, arg2, arg3);
}

export function BindSongToFolder(arg1) {
  return window['go']['main']['App']['BindSongToFolder'](arg1);
}

export function CancelDownloadTask(arg1) {
  return window['go']['main']['App']['CancelDownloadTask'](arg1);
}

export function ChooseBeatorajaDirectory() {
  return window['go']['main']['App']['ChooseBeatorajaDirectory']();
}

export function DelDiffTableHeader(arg1) {
  return window['go']['main']['App']['DelDiffTableHeader'](arg1);
}

export function DelFolder(arg1) {
  return window['go']['main']['App']['DelFolder'](arg1);
}

export function DelFolderContent(arg1) {
  return window['go']['main']['App']['DelFolderContent'](arg1);
}

export function DelRivalInfo(arg1) {
  return window['go']['main']['App']['DelRivalInfo'](arg1);
}

export function DeleteCustomDiffTable(arg1) {
  return window['go']['main']['App']['DeleteCustomDiffTable'](arg1);
}

export function DeleteRivalTagByID(arg1) {
  return window['go']['main']['App']['DeleteRivalTagByID'](arg1);
}

export function FindCourseInfoList() {
  return window['go']['main']['App']['FindCourseInfoList']();
}

export function FindCourseInfoListWithRival(arg1) {
  return window['go']['main']['App']['FindCourseInfoListWithRival'](arg1);
}

export function FindCustomCourseList(arg1) {
  return window['go']['main']['App']['FindCustomCourseList'](arg1);
}

export function FindCustomDiffTableByID(arg1) {
  return window['go']['main']['App']['FindCustomDiffTableByID'](arg1);
}

export function FindCustomDiffTableList(arg1) {
  return window['go']['main']['App']['FindCustomDiffTableList'](arg1);
}

export function FindDiffTableHeaderList() {
  return window['go']['main']['App']['FindDiffTableHeaderList']();
}

export function FindDiffTableHeaderListWithRival(arg1) {
  return window['go']['main']['App']['FindDiffTableHeaderListWithRival'](arg1);
}

export function FindDiffTableHeaderTree(arg1) {
  return window['go']['main']['App']['FindDiffTableHeaderTree'](arg1);
}

export function FindDiffTableHeaderTreeWithRival(arg1) {
  return window['go']['main']['App']['FindDiffTableHeaderTreeWithRival'](arg1);
}

export function FindDownloadTaskList() {
  return window['go']['main']['App']['FindDownloadTaskList']();
}

export function FindFolderContentList(arg1) {
  return window['go']['main']['App']['FindFolderContentList'](arg1);
}

export function FindFolderList(arg1) {
  return window['go']['main']['App']['FindFolderList'](arg1);
}

export function FindFolderTree(arg1) {
  return window['go']['main']['App']['FindFolderTree'](arg1);
}

export function FindRivalInfoList() {
  return window['go']['main']['App']['FindRivalInfoList']();
}

export function FindRivalTagList(arg1) {
  return window['go']['main']['App']['FindRivalTagList'](arg1);
}

export function GENERATE_RIVAL_SCORE_LOG() {
  return window['go']['main']['App']['GENERATE_RIVAL_SCORE_LOG']();
}

export function GENERATE_RIVAL_SONG_DATA_DTO() {
  return window['go']['main']['App']['GENERATE_RIVAL_SONG_DATA_DTO']();
}

export function GENERATE_RIVAL_TAG() {
  return window['go']['main']['App']['GENERATE_RIVAL_TAG']();
}

export function GENERATE_RIVAL_TAG_DTO() {
  return window['go']['main']['App']['GENERATE_RIVAL_TAG_DTO']();
}

export function GENERATOR_BEATORAJA_DIRECTORY_META() {
  return window['go']['main']['App']['GENERATOR_BEATORAJA_DIRECTORY_META']();
}

export function GENERATOR_COURSE_INFO() {
  return window['go']['main']['App']['GENERATOR_COURSE_INFO']();
}

export function GENERATOR_COURSE_INFO_DTO() {
  return window['go']['main']['App']['GENERATOR_COURSE_INFO_DTO']();
}

export function GENERATOR_CUSTOM_COUSE() {
  return window['go']['main']['App']['GENERATOR_CUSTOM_COUSE']();
}

export function GENERATOR_CUSTOM_COUSE_DATA() {
  return window['go']['main']['App']['GENERATOR_CUSTOM_COUSE_DATA']();
}

export function GENERATOR_CUSTOM_DIFF_TABLE_DTO() {
  return window['go']['main']['App']['GENERATOR_CUSTOM_DIFF_TABLE_DTO']();
}

export function GENERATOR_DOWNLOAD_SOURCE() {
  return window['go']['main']['App']['GENERATOR_DOWNLOAD_SOURCE']();
}

export function GENERATOR_DOWNLOAD_TASK() {
  return window['go']['main']['App']['GENERATOR_DOWNLOAD_TASK']();
}

export function GENERATOR_FOLDER() {
  return window['go']['main']['App']['GENERATOR_FOLDER']();
}

export function GENERATOR_FOLDER_CONTENT_DTO() {
  return window['go']['main']['App']['GENERATOR_FOLDER_CONTENT_DTO']();
}

export function GENERATOR_FOLDER_DTO() {
  return window['go']['main']['App']['GENERATOR_FOLDER_DTO']();
}

export function GENERATOR_KEY_COUNT_DTO() {
  return window['go']['main']['App']['GENERATOR_KEY_COUNT_DTO']();
}

export function GENERATOR_NOTIFICATION_DTO() {
  return window['go']['main']['App']['GENERATOR_NOTIFICATION_DTO']();
}

export function GENERATOR_PREDEFINE_TABLE_HEADER() {
  return window['go']['main']['App']['GENERATOR_PREDEFINE_TABLE_HEADER']();
}

export function GENERATOR_PREDEFINE_TABLE_SCHEME() {
  return window['go']['main']['App']['GENERATOR_PREDEFINE_TABLE_SCHEME']();
}

export function GENERATOR_RIVAL_INFO() {
  return window['go']['main']['App']['GENERATOR_RIVAL_INFO']();
}

export function GENERATOR_RIVAL_INFO_DTO() {
  return window['go']['main']['App']['GENERATOR_RIVAL_INFO_DTO']();
}

export function GENERATOR_TABLE_DATA() {
  return window['go']['main']['App']['GENERATOR_TABLE_DATA']();
}

export function GENERATOR_TABLE_HEADER() {
  return window['go']['main']['App']['GENERATOR_TABLE_HEADER']();
}

export function GENERATOR_TABLE_HEADER_DTO() {
  return window['go']['main']['App']['GENERATOR_TABLE_HEADER_DTO']();
}

export function GENERATOR_TABLE_TAG_DTO() {
  return window['go']['main']['App']['GENERATOR_TABLE_TAG_DTO']();
}

export function InitializeMainUser(arg1) {
  return window['go']['main']['App']['InitializeMainUser'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function QueryCourseSongListWithRival(arg1) {
  return window['go']['main']['App']['QueryCourseSongListWithRival'](arg1);
}

export function QueryCurrentDownloadSource() {
  return window['go']['main']['App']['QueryCurrentDownloadSource']();
}

export function QueryCustomCourseSongListWithRival(arg1) {
  return window['go']['main']['App']['QueryCustomCourseSongListWithRival'](arg1);
}

export function QueryCustomDiffTablePageList(arg1) {
  return window['go']['main']['App']['QueryCustomDiffTablePageList'](arg1);
}

export function QueryDiffTableDataWithRival(arg1) {
  return window['go']['main']['App']['QueryDiffTableDataWithRival'](arg1);
}

export function QueryDiffTableInfoById(arg1) {
  return window['go']['main']['App']['QueryDiffTableInfoById'](arg1);
}

export function QueryDiffTableInfoWithRival(arg1, arg2) {
  return window['go']['main']['App']['QueryDiffTableInfoWithRival'](arg1, arg2);
}

export function QueryFolderContentWithRival(arg1) {
  return window['go']['main']['App']['QueryFolderContentWithRival'](arg1);
}

export function QueryLatestVersion() {
  return window['go']['main']['App']['QueryLatestVersion']();
}

export function QueryLevelLayeredDiffTableInfoByID(arg1) {
  return window['go']['main']['App']['QueryLevelLayeredDiffTableInfoByID'](arg1);
}

export function QueryMainUser() {
  return window['go']['main']['App']['QueryMainUser']();
}

export function QueryPredefineTableSchemes() {
  return window['go']['main']['App']['QueryPredefineTableSchemes']();
}

export function QueryPrevDayScoreLogList(arg1) {
  return window['go']['main']['App']['QueryPrevDayScoreLogList'](arg1);
}

export function QueryPreviewURLByMd5(arg1) {
  return window['go']['main']['App']['QueryPreviewURLByMd5'](arg1);
}

export function QueryRivalInfoPageList(arg1) {
  return window['go']['main']['App']['QueryRivalInfoPageList'](arg1);
}

export function QueryRivalPlayedYears(arg1) {
  return window['go']['main']['App']['QueryRivalPlayedYears'](arg1);
}

export function QueryRivalScoreLogPageList(arg1) {
  return window['go']['main']['App']['QueryRivalScoreLogPageList'](arg1);
}

export function QueryRivalTagPageList(arg1) {
  return window['go']['main']['App']['QueryRivalTagPageList'](arg1);
}

export function QuerySongDataPageList(arg1) {
  return window['go']['main']['App']['QuerySongDataPageList'](arg1);
}

export function QueryUserInfoByID(arg1) {
  return window['go']['main']['App']['QueryUserInfoByID'](arg1);
}

export function QueryUserInfoWithLevelLayeredDiffTableLampStatus(arg1, arg2) {
  return window['go']['main']['App']['QueryUserInfoWithLevelLayeredDiffTableLampStatus'](arg1, arg2);
}

export function QueryUserKeyCountInYear(arg1) {
  return window['go']['main']['App']['QueryUserKeyCountInYear'](arg1);
}

export function QueryUserPlayCountInYear(arg1, arg2) {
  return window['go']['main']['App']['QueryUserPlayCountInYear'](arg1, arg2);
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function ReloadDiffTableHeader(arg1) {
  return window['go']['main']['App']['ReloadDiffTableHeader'](arg1);
}

export function ReloadRivalData(arg1, arg2) {
  return window['go']['main']['App']['ReloadRivalData'](arg1, arg2);
}

export function ReloadRivalSongData() {
  return window['go']['main']['App']['ReloadRivalSongData']();
}

export function RestartDownloadTask(arg1) {
  return window['go']['main']['App']['RestartDownloadTask'](arg1);
}

export function RevertRivalTagEnabledState(arg1) {
  return window['go']['main']['App']['RevertRivalTagEnabledState'](arg1);
}

export function RunServer() {
  return window['go']['main']['App']['RunServer']();
}

export function SetScoreLogFilePath(arg1) {
  return window['go']['main']['App']['SetScoreLogFilePath'](arg1);
}

export function SubmitDownloadTask(arg1, arg2) {
  return window['go']['main']['App']['SubmitDownloadTask'](arg1, arg2);
}

export function SubmitSingleMD5DownloadTask(arg1, arg2) {
  return window['go']['main']['App']['SubmitSingleMD5DownloadTask'](arg1, arg2);
}

export function SupplyMissingBMSFromTable(arg1) {
  return window['go']['main']['App']['SupplyMissingBMSFromTable'](arg1);
}

export function SyncRivalTag(arg1) {
  return window['go']['main']['App']['SyncRivalTag'](arg1);
}

export function UpdateCustomCourseDataOrder(arg1) {
  return window['go']['main']['App']['UpdateCustomCourseDataOrder'](arg1);
}

export function UpdateCustomCourseOrder(arg1) {
  return window['go']['main']['App']['UpdateCustomCourseOrder'](arg1);
}

export function UpdateCustomDiffTable(arg1) {
  return window['go']['main']['App']['UpdateCustomDiffTable'](arg1);
}

export function UpdateDiffTableHeader(arg1) {
  return window['go']['main']['App']['UpdateDiffTableHeader'](arg1);
}

export function UpdateFolderOrder(arg1) {
  return window['go']['main']['App']['UpdateFolderOrder'](arg1);
}

export function UpdateHeaderLevelOrders(arg1) {
  return window['go']['main']['App']['UpdateHeaderLevelOrders'](arg1);
}

export function UpdateHeaderOrder(arg1) {
  return window['go']['main']['App']['UpdateHeaderOrder'](arg1);
}

export function UpdateRivalInfo(arg1) {
  return window['go']['main']['App']['UpdateRivalInfo'](arg1);
}

export function UpdateRivalReverseImportInfo(arg1) {
  return window['go']['main']['App']['UpdateRivalReverseImportInfo'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
