name: Wails build

on:
  push:
    tags:
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    permissions: write-all
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "lampghost_linux"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "lampghost_windows"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "lampghost"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Initialize xvfb
        if: ${{ matrix.build.os == 'ubuntu-latest' }}
        run: |
          sudo apt install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=':99.0'
          echo $DISPLAY

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        with:
          DISPLAY: ":99.0"
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: "1.24.5"
          wails-version: "v2.10.2"
